title: "Development Log"
author: "RoseSecurity"
description: "A blog about development, security, and other nerdy things."

github_username: "RoseSecurity"
linkedin_username: "RoseSecurity"

remote_theme: pages-themes/cayman@v0.2.0

rss: RSS

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
